context:
  version: "8.1.1"

package:
  name: titanium
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/titanium/-/titanium-${{ version }}.tgz
  sha256: 1214f3424197a55d69ecb8552c342448e25450cfc727eb96dc06e6f9dd1d6813

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - titanium --help

about:
  license: Apache-2.0
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: Command line interface for building Titanium SDK apps
  homepage: https://titaniumsdk.com/https://jshint.com
  repository: https://github.com/tidev/titanium-cli

extra:
  recipe-maintainers:
    - danielnachun
