context:
  version: "7.1.6"

package:
  name: titanium
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/titanium/-/titanium-${{ version }}.tgz
  sha256: 799c8db961e2cef7d3b379198ac0eac8c5f12327c18a16cd07ee5b81c5796782

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - titanium --help

about:
  license: Apache-2.0
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: Command line interface for building Titanium SDK apps
  homepage: https://titaniumsdk.com/https://jshint.com
  repository: https://github.com/tidev/titanium-cli

extra:
  recipe-maintainers:
    - danielnachun
