context:
  version: "8.1.3"

package:
  name: titanium
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/titanium/-/titanium-${{ version }}.tgz
  sha256: d06caaa1aa2fe23c00161f436bfa33c948778f107da0fad29ee520d071afe315

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - titanium --help

about:
  license: Apache-2.0
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: Command line interface for building Titanium SDK apps
  homepage: https://titaniumsdk.com/https://jshint.com
  repository: https://github.com/tidev/titanium-cli

extra:
  recipe-maintainers:
    - danielnachun
