context:
  version: "9.0.0"

package:
  name: titanium
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/titanium/-/titanium-${{ version }}.tgz
  sha256: 534d21aa6733770918f06dfc643f726235c2953c11b10c875b2a2719c0afc3b9

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - titanium --help

about:
  license: Apache-2.0
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: Command line interface for building Titanium SDK apps
  homepage: https://titaniumsdk.com/https://jshint.com
  repository: https://github.com/tidev/titanium-cli

extra:
  recipe-maintainers:
    - danielnachun
